2020-03-27 12:17:43,128 ERROR: Exception on /category2/Politics [GET] [in /Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: news.title

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/routes.py", line 334, in category2
    json2db.dbimport(json_path)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/json2db.py", line 45, in dbimport
    db.session.commit()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: news.title
[SQL: INSERT INTO news (outlet, category, title, link, summary) VALUES (?, ?, ?, ?, ?)]
[parameters: ('theguardian', 'Entertaniment & Arts', 'Olivier awards replaces cancelled ceremony with greatest moments show', 'https://www.theguardian.com/stage/2020/mar/25/olivier-awards-cancelled-ceremony-with-greatest-hits-show', 'Jason Manford will present programme of past highlights from the awards show, which has been postponed this year due to the coronavirus outbreakThe O ... (591 characters truncated) ...  will be broadcast on ITV on Sunday 5 April at 10.15pm. Magic Radio will broadcast its own two-hour celebration from 6pm to 8pm on the same evening. ')]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-03-27 12:20:04,363 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 12:20:55,253 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 12:26:02,683 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 12:58:53,021 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 13:00:21,868 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 13:00:56,025 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 13:04:45,954 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 13:05:49,492 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 13:06:28,307 INFO: News Aggregation startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 13:09:26,537 INFO: News Aggregation startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 13:10:02,859 INFO: News Aggregation startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 13:17:36,673 INFO: News Aggregation startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
