2020-03-27 16:51:57,645 ERROR: Exception on /category2/Politics [GET] [in /Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/routes.py", line 341, in category2
    next_url = url_for('category2', page=allnew.next_num)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'category2' with values ['page']. Did you forget to specify values ['category']?
2020-03-27 16:55:46,360 INFO: News Aggregation startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 16:55:51,664 ERROR: Exception on /category2/Politics [GET] [in /Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/routes.py", line 341, in category2
    next_url = url_for('category2', page=allnew.next_num)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'category2' with values ['page']. Did you forget to specify values ['category']?
2020-03-27 16:55:54,832 ERROR: Exception on /category2/Politics [GET] [in /Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/routes.py", line 341, in category2
    next_url = url_for('category2', page=allnew.next_num)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'category2' with values ['page']. Did you forget to specify values ['category']?
2020-03-27 16:59:19,747 INFO: News Aggregation startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-27 16:59:28,632 ERROR: Exception on /category2/Politics [GET] [in /Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/routes.py", line 352, in category2
    for new in allnew:
TypeError: 'Pagination' object is not iterable
