2020-03-26 18:44:05,887 ERROR: Exception on /category/Sport [GET] [in /Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/routes.py", line 235, in category
    return render_template("category.html", category = aaa, news = news_list)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/templates/category.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/templates/base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/templates/category.html", line 19, in block "app_content"
    {%for item in news%}
TypeError: 'NoneType' object is not iterable
2020-03-26 18:45:04,567 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:45:34,385 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:46:07,074 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:46:11,046 ERROR: Exception on /category/Sport [GET] [in /Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/routes.py", line 216, in category
    news_list = new_list.reverse()[0:100]
TypeError: 'NoneType' object is not subscriptable
2020-03-26 18:47:48,259 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:50:19,637 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:52:12,929 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:52:44,757 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:53:54,911 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:54:21,181 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 18:55:15,751 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 19:01:21,620 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 19:01:26,163 ERROR: Exception on /category/Politics [GET] [in /Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/routes.py", line 213, in category
    stories.append((category2,link,title,summary, outlet_relevent))
NameError: name 'outlet_relevent' is not defined
2020-03-26 19:01:47,618 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 19:05:44,594 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
2020-03-26 22:27:01,457 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system-Iteration3/news_agg_app/app/__init__.py:49]
